### PR TITLE
Improve the query and script to display many missing lighthouses and add a Github action to update the data daily

### LINKED ISSUE #1: Also capture sectored lights
https://wiki.openstreetmap.org/wiki/Seamarks/Sectored_and_Directional_Lights

### LINKED ISSUE #4: Enrichment: Great Lakes Lighthouses
Most of the Great Lakes' lighthouses are missing from this map. I found the data shared by the Great Lakes Lighthouse Keepers Association here.

https://gllka.maps.arcgis.com/apps/webappviewer/index.html?id=9e1508ae15f9444f9b960aa42e435951&fbclid=IwAR1w5ukx_Rn2PoK6-2bDHygJlOh8uOLLL4zzvRIso7sa0-oMarEWxApgsK0

### LINKED ISSUE #5: Enrichment: Maine Lighthouses and other New England Lighthouses
The clusters of lighthouses in the U.S. that would be nice to complete first are in the Great Lakes and in the Northeast (New England, esp. Maine).

### LINKED ISSUE #13: Fix range for "Tjuvviki" beacon light (Giant red circle in Norway)
The "Tjuvviki" beacon in data-full.json shows a range of 33 Nautical miles which is a mistake that can be traces back to the API that served the data. The correct range should be a much smaller 2 miles according to [this pdf](https://msi.nga.mil/api/publications/download?key=16694312/SFH00000/UpdatedPub115bk.pdf&type=view). You can find it in the PDF if you search for "Tjuviki" (slightly different spelling than the API has but the same coordiantes). You can either just edit your json file or try repulling from the API, but I am not certain I went about fixing the range correctly, so it may or may not be fixed on their side.

### LINKED ISSUE #15: Missing - Tybee Island lighthouse
https://g.page/tybeelighthouse?share

### LINKED ISSUE #17: Formentera lights missing
South east and west side of Formentera has lighthouses with lights.

### LINKED ISSUE #18: Westerhever missing
Westerhever lighthouse is missing on the map? Is there missing any required metadata on OSM?
https://www.openstreetmap.org/way/87534169

### PR DESCRIPTION
**Pull request by PierreMesure**
I discovered your brilliant project through [this tweet](https://twitter.com/emollick/status/1485467613190832130) yesterday evening and I spent a few hours trying to display missing lighthouses on the map!

This PR does 3 things:
- Add a Github Action that fetches the data every 24h
- Updates the data and includes objects with several lights, i.e. lighthouses with the `seamark:light:1:` and no `seamark:light:`
- Rename the properties of these objects so they can be processed by the script and displayed on the map

It turns out most lighthouses have several lights and they weren't even fetched from OpenStreetMap. This PR fixes that, albeit in a basic way since these new additions are only blinking as their first light is, the other lights are not taken into account.

Have a look at the result [here](https://pierremesure.github.io/lighthousemap/) and see if you can find the lighthouse that you couldn't find on the original map!

### CODE REVIEW

**Comment by PierreMesure** [comment]
This branch contains some undesired changes (such as my additions to the README). I can clean them once I've gotten confirmation that you're interested in merging it.

**Comment by brianboru82** [comment]
Hi, thank you for adding a action to update the dataset! Though I see the update action has failed the past few days. If I try to run the overpass query myself, it works fine, but takes a while. Maybe the timeout needs to be increased?

**Comment by jamesscottbrown** [comment]
I don't think the problem is due to a timeout.

The logs report:

>Run wget -O data-full.json https://www.overpass-api.de/api/interpreter?data=%0A%09%09%09%5Bout%3Ajson%5D%5Btimeout%3A300%5D%3B%0A%09%09%09(%0A%09%09%09%20%20node%5B%22seamark%3Alight%3Asequence%22%5D(-90%2C-180%2C90%2C180)%3B%0A%09%09%09%20%20node%5B%22seamark%3Alight%3A1%3Asequence%22%5D(-90%2C-180%2C90%2C180)%3B%0A%09%09%09%20%20way%5B%22seamark%3Alight%3Asequence%22%5D(-90%2C-180%2C90%2C180)%3B%0A%09%09%09%20%20way%5B%22seamark%3Alight%3A1%3Asequence%22%5D(-90%2C-180%2C90%2C180)%3B%0A%09%09%09)%3B%0A%09%09%09out%20body%3B%0A%09%09%09%3E%3B%0A%09%09%09out%20skel%20qt%3B%0A%09%09

> /home/runner/work/_temp/d420fe00-78c7-4e54-bc95-5f7e2525da1f.sh: line 1: syntax error near unexpected token `('

I think the URL needs to be enclosed in quotation marks in `.github/workflows/update_data.yml`. I've opened a PR against @PierreMesure's `master` branch to fix this.

**Comment by PierreMesure** [comment]
Thank you @jamesscottbrown, your fix worked!

**Pull request merged**
